version: '3.8'
services:
  web:
    build: .
    ports:
      - "80:80"         # nginx จะฟัง port 80
      - "3000:3000"     # Next.js
      - "8000:8000"     # Django
    depends_on:
      - db

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypass
      POSTGRES_DB: mydb
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
